version: '3.9'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0.11
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ../../config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
